#ifndef PERFORMENCETEST_GLOBAL_H
#define PERFORMENCETEST_GLOBAL_H

#ifdef PERFORMENCETEST_LIB
# define PERFORMENCETEST_EXPORT __declspec(dllexport)
#else
# define PERFORMENCETEST_EXPORT __declspec(dllimport)
#endif

#endif // PERFORMENCETEST_GLOBAL_H
