#ifndef PERFORMENCETEST_GLOBAL_H
#define PERFORMENCETEST_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef PERFORMENCETEST_LIB
# define PERFORMENCETEST_EXPORT Q_DECL_EXPORT
#else
# define PERFORMENCETEST_EXPORT Q_DECL_IMPORT
#endif

#endif // PERFORMENCETEST_GLOBAL_H
